<?php
declare(strict_types=1);

/**
 * One-time web installer: writes inc/config.php, creates tables, seeds data, creates the first admin.
 * Locked automatically once inc/config.php exists.
 */

require __DIR__ . '/inc/bootstrap.php';
require INC_PATH . '/content.php';
require_once INC_PATH . '/schema.php';
require INC_PATH . '/seed.php';

$locked = is_installed();
$error = null;
$done = false;
$old = $_POST + ['db_host' => 'localhost', 'db_port' => '3306', 'app_url' => 'https://' . COMPANY['domain'],
    'admin_name' => 'Dev Integra Code', 'admin_email' => 'dev@integra-code.tech', 'admin2_name' => 'Leiva', 'admin2_email' => 'leiva@integra-code.tech'];

if (!$locked && $_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $email = mb_strtolower(trim((string)($_POST['admin_email'] ?? '')));
        $password = (string)($_POST['admin_password'] ?? '');
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) throw new RuntimeException('E-mail do administrador inválido.');
        if (mb_strlen($password) < 10) throw new RuntimeException('A senha do administrador precisa ter pelo menos 10 caracteres.');
        $email2 = mb_strtolower(trim((string)($_POST['admin2_email'] ?? '')));
        $password2 = (string)($_POST['admin2_password'] ?? '');
        if ($password2 !== '' && (!filter_var($email2, FILTER_VALIDATE_EMAIL) || mb_strlen($password2) < 10)) {
            throw new RuntimeException('Segundo administrador: informe um e-mail válido e senha com 10+ caracteres (ou deixe a senha em branco para não criar).');
        }

        $config = [
            'app_url' => rtrim(trim((string)$_POST['app_url']), '/'),
            'app_key' => bin2hex(random_bytes(32)),
            'debug' => false,
            'db' => [
                'driver' => 'mysql',
                'host' => trim((string)$_POST['db_host']),
                'port' => (int)$_POST['db_port'],
                'name' => trim((string)$_POST['db_name']),
                'user' => trim((string)$_POST['db_user']),
                'pass' => (string)$_POST['db_pass'],
            ],
        ];
        $GLOBALS['config'] = $config;
        db(); // throws on bad credentials
        run_migrations();
        seed_base();
        set_setting('schema_version', (string)SCHEMA_VERSION);
        if (!db_value('SELECT id FROM users WHERE email = ?', [$email])) {
            db_insert('users', [
                'name' => trim((string)($_POST['admin_name'] ?? 'Administrador')) ?: 'Administrador',
                'email' => $email, 'password_hash' => password_hash($password, PASSWORD_DEFAULT),
                'role' => 'admin', 'active' => 1, 'created_at' => now(),
            ]);
        }
        if ($password2 !== '' && !db_value('SELECT id FROM users WHERE email = ?', [$email2])) {
            db_insert('users', [
                'name' => trim((string)($_POST['admin2_name'] ?? '')) ?: 'Administrador',
                'email' => $email2, 'password_hash' => password_hash($password2, PASSWORD_DEFAULT),
                'role' => 'admin', 'active' => 1, 'created_at' => now(),
            ]);
        }
        $cfAccount = preg_replace('/[^a-f0-9]/', '', (string)($_POST['cloudflare_account_id'] ?? ''));
        $cfToken = trim((string)($_POST['cloudflare_api_token'] ?? ''));
        if ($cfAccount !== '' && $cfToken !== '') {
            set_setting('cloudflare_account_id', $cfAccount);
            set_setting('cloudflare_api_token', $cfToken);
        }
        $asaasKey = trim((string)($_POST['asaas_api_key'] ?? ''));
        if ($asaasKey !== '') {
            set_setting('asaas_api_key', $asaasKey);
            set_setting('asaas_environment', ($_POST['asaas_environment'] ?? '') === 'sandbox' ? 'sandbox' : 'production');
        }
        $php = "<?php\n// Generated by install.php on " . date('c') . ". Keep this file private.\nreturn " . var_export($config, true) . ";\n";
        if (file_put_contents(INC_PATH . '/config.php', $php, LOCK_EX) === false) {
            throw new RuntimeException('Não foi possível gravar inc/config.php. Verifique as permissões da pasta.');
        }
        @chmod(INC_PATH . '/config.php', 0600);
        $done = true;
    } catch (PDOException $e) {
        $error = 'Falha ao conectar no banco de dados: ' . $e->getMessage();
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}
?><!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Instalação · Integra Code</title>
<link rel="icon" href="/assets/img/favicon.svg">
<link rel="stylesheet" href="/admin/app.css">
</head>
<body class="auth-body">
<main class="auth-card" style="max-width:560px">
  <img src="/assets/img/logo-dark.svg" alt="Integra Code" class="auth-logo" style="height:46px">
  <?php if ($locked && !$done): ?>
    <h1>Instalação concluída</h1>
    <p class="muted">O sistema já está instalado. Por segurança, exclua o arquivo <code>install.php</code> do servidor.</p>
    <a class="btn btn-primary btn-block" href="/admin/">Ir para o painel</a>
  <?php elseif ($done): ?>
    <h1>Tudo pronto! 🎉</h1>
    <p class="muted">Banco criado e administrador cadastrado. <strong>Exclua agora o arquivo <code>install.php</code></strong> pelo Gerenciador de Arquivos da Hostinger.</p>
    <a class="btn btn-primary btn-block" href="/admin/">Acessar o painel</a>
  <?php else: ?>
    <h1>Instalar Integra Code</h1>
    <p class="muted">Crie um banco MySQL no hPanel da Hostinger (Bancos de dados → MySQL) e preencha os dados abaixo.</p>
    <?php if ($error): ?><div class="alert alert-danger"><?= e($error) ?></div><?php endif; ?>
    <form method="post" class="form-grid">
      <fieldset class="span-2"><legend>Site</legend>
        <label>URL do site<input name="app_url" value="<?= e($old['app_url']) ?>" required></label>
      </fieldset>
      <fieldset class="span-2"><legend>Banco de dados MySQL</legend>
        <div class="form-grid">
          <label>Host<input name="db_host" value="<?= e($old['db_host']) ?>" required></label>
          <label>Porta<input name="db_port" value="<?= e($old['db_port']) ?>" required></label>
          <label>Nome do banco<input name="db_name" value="<?= e($old['db_name'] ?? '') ?>" placeholder="u123456789_integra" required></label>
          <label>Usuário<input name="db_user" value="<?= e($old['db_user'] ?? '') ?>" required></label>
          <label class="span-2">Senha<input name="db_pass" type="password" required></label>
        </div>
      </fieldset>
      <fieldset class="span-2"><legend>Administrador</legend>
        <div class="form-grid">
          <label>Nome<input name="admin_name" value="<?= e($old['admin_name'] ?? '') ?>" required></label>
          <label>E-mail<input name="admin_email" type="email" value="<?= e($old['admin_email'] ?? '') ?>" required></label>
          <label class="span-2">Senha (mín. 10 caracteres)<input name="admin_password" type="password" minlength="10" required></label>
        </div>
      </fieldset>
      <fieldset class="span-2"><legend>Segundo administrador (opcional)</legend>
        <div class="form-grid">
          <label>Nome<input name="admin2_name" value="<?= e($old['admin2_name']) ?>"></label>
          <label>E-mail<input name="admin2_email" type="email" value="<?= e($old['admin2_email']) ?>"></label>
          <label class="span-2">Senha (deixe em branco para não criar)<input name="admin2_password" type="password" minlength="10"></label>
        </div>
      </fieldset>
      <fieldset class="span-2"><legend>Asaas (opcional — pode configurar depois no painel)</legend>
        <div class="form-grid">
          <label>Ambiente<select name="asaas_environment" style="width:100%;padding:11px 13px;border-radius:10px;border:1px solid var(--border-strong);background:var(--bg-2)"><option value="production">Produção</option><option value="sandbox">Sandbox</option></select></label>
          <label>Chave da API<input name="asaas_api_key" autocomplete="off" placeholder="$aact_prod_..."></label>
        </div>
      </fieldset>
      <fieldset class="span-2"><legend>IA — Cloudflare Workers AI (opcional)</legend>
        <div class="form-grid">
          <label>Account ID<input name="cloudflare_account_id" autocomplete="off"></label>
          <label>API Token<input name="cloudflare_api_token" autocomplete="off" placeholder="cfat_..."></label>
        </div>
      </fieldset>
      <button class="btn btn-primary btn-block span-2">Instalar</button>
    </form>
  <?php endif; ?>
</main>
</body>
</html>
