<?php
declare(strict_types=1);

/**
 * Schema v9 — Integra Fiscal Hub financial module for customers: bank accounts, categories,
 * payables/receivables, bank statement lines (OFX / Open Finance) and reconciliation.
 * Owned by inc/fiscalhub_finance.php. Portable SQL (SQLite, MySQL 8, MariaDB 10.6+).
 */

function fh_schema_fin(string $pk, string $fk, string $text): array
{
    return [
        'tables' => [
            'fh_fin_accounts' => "
                id $pk,
                customer_id $fk NOT NULL,
                emitter_id $fk NULL,
                name VARCHAR(120) NOT NULL,
                kind VARCHAR(20) NOT NULL DEFAULT 'checking',
                bank_code VARCHAR(10) NULL,
                bank_name VARCHAR(120) NULL,
                agency VARCHAR(20) NULL,
                account_number VARCHAR(30) NULL,
                opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0,
                opening_date DATE NULL,
                color VARCHAR(20) NULL,
                connection_id $fk NULL,
                external_id VARCHAR(80) NULL,
                last_sync_at DATETIME NULL,
                stmt_balance DECIMAL(14,2) NULL,
                stmt_balance_date DATE NULL,
                active TINYINT NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL",

            'fh_fin_categories' => "
                id $pk,
                customer_id $fk NOT NULL,
                kind VARCHAR(10) NOT NULL,
                name VARCHAR(120) NOT NULL,
                parent_id $fk NULL,
                dre_group VARCHAR(30) NULL,
                color VARCHAR(20) NULL,
                sector_key VARCHAR(40) NULL,
                active TINYINT NOT NULL DEFAULT 1,
                position INT NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL",

            'fh_fin_entries' => "
                id $pk,
                customer_id $fk NOT NULL,
                emitter_id $fk NULL,
                kind VARCHAR(10) NOT NULL,
                description VARCHAR(255) NOT NULL,
                category_id $fk NULL,
                account_id $fk NULL,
                party_name VARCHAR(200) NULL,
                party_document VARCHAR(20) NULL,
                taker_id $fk NULL,
                invoice_id $fk NULL,
                nfe_doc_id $fk NULL,
                amount DECIMAL(14,2) NOT NULL,
                due_date DATE NOT NULL,
                competence_date DATE NULL,
                status VARCHAR(10) NOT NULL DEFAULT 'open',
                paid_at DATE NULL,
                paid_amount DECIMAL(14,2) NULL,
                interest DECIMAL(14,2) NOT NULL DEFAULT 0,
                discount DECIMAL(14,2) NOT NULL DEFAULT 0,
                payment_method VARCHAR(20) NULL,
                document_number VARCHAR(60) NULL,
                installment INT NULL,
                installments INT NULL,
                series_key VARCHAR(40) NULL,
                recurrence VARCHAR(10) NULL,
                cost_center VARCHAR(120) NULL,
                tags VARCHAR(255) NULL,
                notes TEXT NULL,
                origin VARCHAR(12) NOT NULL DEFAULT 'manual',
                transaction_id $fk NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL",

            'fh_fin_connections' => "
                id $pk,
                customer_id $fk NOT NULL,
                provider VARCHAR(20) NOT NULL DEFAULT 'pluggy',
                label VARCHAR(120) NULL,
                item_id VARCHAR(80) NULL,
                credentials TEXT NULL,
                connector_id VARCHAR(40) NULL,
                connector_name VARCHAR(120) NULL,
                status VARCHAR(30) NULL,
                error_message TEXT NULL,
                consent_expires_at DATETIME NULL,
                last_sync_at DATETIME NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL",

            'fh_fin_imports' => "
                id $pk,
                customer_id $fk NOT NULL,
                account_id $fk NOT NULL,
                source VARCHAR(20) NOT NULL,
                file_name VARCHAR(190) NULL,
                period_start DATE NULL,
                period_end DATE NULL,
                count_new INT NOT NULL DEFAULT 0,
                count_dup INT NOT NULL DEFAULT 0,
                balance DECIMAL(14,2) NULL,
                balance_date DATE NULL,
                created_at DATETIME NOT NULL",

            'fh_fin_transactions' => "
                id $pk,
                customer_id $fk NOT NULL,
                account_id $fk NOT NULL,
                source VARCHAR(20) NOT NULL,
                external_id VARCHAR(120) NULL,
                import_id $fk NULL,
                tx_date DATE NOT NULL,
                amount DECIMAL(14,2) NOT NULL,
                description VARCHAR(255) NOT NULL,
                memo VARCHAR(255) NULL,
                doc_number VARCHAR(60) NULL,
                balance DECIMAL(14,2) NULL,
                category_id $fk NULL,
                entry_id $fk NULL,
                status VARCHAR(12) NOT NULL DEFAULT 'pending',
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL",

            'fh_fin_rules' => "
                id $pk,
                customer_id $fk NOT NULL,
                match_text VARCHAR(120) NOT NULL,
                direction VARCHAR(10) NULL,
                category_id $fk NULL,
                party_name VARCHAR(200) NULL,
                hits INT NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL",

            // v11: automatic recurring payables/receivables (templates; see inc/fiscalhub_fin_recurring.php)
            'fh_fin_recurring' => "
                id $pk,
                customer_id $fk NOT NULL,
                emitter_id $fk NULL,
                kind VARCHAR(10) NOT NULL,
                description VARCHAR(255) NOT NULL,
                amount DECIMAL(14,2) NOT NULL,
                category_id $fk NULL,
                account_id $fk NULL,
                party_name VARCHAR(200) NULL,
                party_document VARCHAR(20) NULL,
                taker_id $fk NULL,
                payment_method VARCHAR(20) NULL,
                cost_center VARCHAR(120) NULL,
                notes TEXT NULL,
                frequency VARCHAR(12) NOT NULL DEFAULT 'monthly',
                day_of_month INT NULL,
                start_date DATE NOT NULL,
                next_due DATE NOT NULL,
                end_date DATE NULL,
                max_occurrences INT NULL,
                generated_count INT NOT NULL DEFAULT 0,
                last_generated DATE NULL,
                lead_days INT NOT NULL DEFAULT 30,
                auto_settle TINYINT NOT NULL DEFAULT 0,
                series_key VARCHAR(40) NULL,
                active TINYINT NOT NULL DEFAULT 1,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL",
        ],
        'indexes' => [
            'idx_fh_fin_acc_customer' => 'fh_fin_accounts (customer_id, active)',
            'idx_fh_fin_cat_customer' => 'fh_fin_categories (customer_id, kind)',
            'idx_fh_fin_entries_due' => 'fh_fin_entries (customer_id, kind, status, due_date)',
            'idx_fh_fin_entries_paid' => 'fh_fin_entries (customer_id, paid_at)',
            'idx_fh_fin_entries_inv' => 'fh_fin_entries (invoice_id)',
            'idx_fh_fin_entries_tx' => 'fh_fin_entries (transaction_id)',
            'idx_fh_fin_tx_account' => 'fh_fin_transactions (account_id, tx_date)',
            'idx_fh_fin_tx_ext' => 'fh_fin_transactions (account_id, source, external_id)',
            'idx_fh_fin_tx_status' => 'fh_fin_transactions (customer_id, status)',
            'idx_fh_fin_conn_customer' => 'fh_fin_connections (customer_id)',
            'idx_fh_fin_rules_customer' => 'fh_fin_rules (customer_id)',
            'idx_fh_fin_rec_customer' => 'fh_fin_recurring (customer_id, active, next_due)',
        ],
        'columns' => [],
    ];
}
